module.exports = {
  name: 'barbour-app',
  cwd: '/app',
  maxInstances: 2,
  script: 'node server/index.mjs',
  args: [],
  instances: 2,
  exec_mode: 'cluster',
  autorestart: true,
  watch: false,
  max_memory_restart: '1G',
  env: {
    NODE_ENV: 'production',
    PORT: 3000,
  },
  env_development: {
    NODE_ENV: 'development',
    PORT: 3000,
  },
  error_file: '/var/log/pm2/app-error.log',
  out_file: '/var/log/pm2/app-out.log',
  log_date_format: 'YYYY-MM-DD HH:mm:ss',
  merge_logs: true,
  min_uptime: '10s',
  max_restarts: 10,
  restart_delay: 4000,
}
